import type { Car } from "./types"

// Mock car data
const cars: Car[] = [
  {
    id: 1,
    brand: "Toyota",
    model: "Camry",
    year: 2023,
    price: 28000,
    image: "https://i.pinimg.com/736x/d3/7a/5f/d37a5f3289d55d0aad6cfc85bbeeb8a1.jpg",
    fuelType: "Gasoline",
    transmission: "Automatic",
    mileage: 5000,
    seatingCapacity: 5,
    description:
      "The Toyota Camry is a reliable and fuel-efficient sedan with modern features and comfortable interior. It offers a smooth ride, excellent safety ratings, and a spacious cabin that comfortably seats five adults. With its reputation for reliability and longevity, the Camry continues to be one of the most popular midsize sedans on the market.",
    features: [
      "Bluetooth Connectivity",
      "Backup Camera",
      "Lane Departure Warning",
      "Adaptive Cruise Control",
      "Apple CarPlay",
      "Android Auto",
      "Dual-Zone Climate Control",
      "LED Headlights",
      "Keyless Entry",
      "Push Button Start",
    ],
  },
  {
    id: 2,
    brand: "Honda",
    model: "Civic",
    year: 2022,
    price: 25000,
    image: "https://i.pinimg.com/736x/f0/ae/cb/f0aecbe53189118c2e76a0a4a1e3767f.jpg",
    fuelType: "Gasoline",
    transmission: "Automatic",
    mileage: 8000,
    seatingCapacity: 5,
    description:
      "The Honda Civic offers excellent fuel economy, a spacious interior, and a smooth ride quality. Known for its reliability and value retention, the Civic provides a balanced combination of performance, comfort, and efficiency. The latest generation features a more refined interior, improved technology, and enhanced driving dynamics that make it a standout in the compact car segment.",
    features: [
      "Touchscreen Infotainment",
      "Wireless Charging",
      "Heated Seats",
      "Sunroof",
      "Blind Spot Monitoring",
      "Honda Sensing Safety Suite",
      "Multi-Angle Rearview Camera",
      "Smart Entry with Walk Away Auto Lock",
      "60/40 Split Fold-Down Rear Seatback",
      "Automatic Climate Control",
    ],
  },
  {
    id: 3,
    brand: "Tesla",
    model: "Model 3",
    year: 2023,
    price: 45000,
    image: "https://i.pinimg.com/736x/c9/4f/de/c94fdeb008bdf6d791cff571154323c9.jpg",
    fuelType: "Electric",
    transmission: "Automatic",
    mileage: 3000,
    seatingCapacity: 5,
    description:
      "The Tesla Model 3 is an all-electric sedan with impressive range, cutting-edge technology, and sporty performance. As Tesla's most affordable vehicle, it brings electric mobility to a wider audience without compromising on the brand's innovative features. The minimalist interior is dominated by a large central touchscreen that controls nearly all vehicle functions, while the instant torque delivery provides exhilarating acceleration.",
    features: [
      "Autopilot",
      "15-inch Touchscreen",
      "360-degree Camera",
      "Glass Roof",
      "Wireless Charging",
      "Premium Sound System",
      "Over-the-air Updates",
      "Sentry Mode",
      "Dog Mode",
      "Camp Mode",
      "Full Self-Driving Capability (Optional)",
    ],
  },
  {
    id: 4,
    brand: "BMW",
    model: "3 Series",
    year: 2022,
    price: 42000,
    image: "https://i.pinimg.com/736x/f3/78/6d/f3786d6e52d006ab37102e1a8f59a71e.jpg",
    fuelType: "Gasoline",
    transmission: "Automatic",
    mileage: 10000,
    seatingCapacity: 5,
    description:
      "The BMW 3 Series combines luxury, performance, and technology in a compact sports sedan package. For decades, the 3 Series has set the standard for the segment with its perfect balance of driving dynamics and premium amenities. The current generation offers a refined interior, state-of-the-art infotainment system, and a range of powerful yet efficient engines.",
    features: [
      "Leather Seats",
      "Navigation System",
      "Harman Kardon Audio",
      "Parking Sensors",
      "Heated Steering Wheel",
      "BMW iDrive 7.0",
      "Gesture Control",
      "Ambient Lighting",
      "Sport Seats",
      "Dynamic Stability Control",
      "Active Driving Assistant",
    ],
  },
  {
    id: 5,
    brand: "Ford",
    model: "F-150",
    year: 2023,
    price: 52000,
    image: "https://i.pinimg.com/736x/5c/9f/86/5c9f86f6d46d2c723f5768a1bdef5d02.jpg",
    fuelType: "Gasoline",
    transmission: "Automatic",
    mileage: 7000,
    seatingCapacity: 6,
    description:
      "The Ford F-150 is a versatile and capable full-size pickup truck with powerful engine options and advanced features. As America's best-selling vehicle for over four decades, the F-150 continues to innovate with features like a hybrid powertrain option, onboard generator, and advanced driver assistance technologies. Its aluminum body construction helps reduce weight while maintaining durability and capability.",
    features: [
      "Pro Power Onboard",
      "Trailer Backup Assist",
      "Tailgate Step",
      "360-degree Camera",
      "Sync 4 Infotainment",
      "Fold-flat Work Surface",
      "Zone Lighting",
      "Onboard Scales",
      "Smart Trailer Tow Connector",
      "Active Drive Assist Prep Kit",
    ],
  },
  {
    id: 6,
    brand: "Chevrolet",
    model: "Equinox",
    year: 2022,
    price: 32000,
    image: "https://i.pinimg.com/736x/7e/37/14/7e37146c5405e144791f5f01ef44960b.jpg",
    fuelType: "Gasoline",
    transmission: "Automatic",
    mileage: 12000,
    seatingCapacity: 5,
    description:
      "The Chevrolet Equinox is a compact SUV offering good fuel economy, a comfortable ride, and plenty of tech features. It strikes a good balance between size and maneuverability, making it ideal for both city driving and longer trips. The Equinox provides a spacious cabin with flexible cargo options and a comprehensive suite of safety features that give drivers peace of mind.",
    features: [
      "Teen Driver Technology",
      "Wi-Fi Hotspot",
      "Automatic Emergency Braking",
      "Rear Cross Traffic Alert",
      "Hands-Free Liftgate",
      "Chevrolet Infotainment 3 System",
      "Apple CarPlay and Android Auto",
      "Rear Seat Reminder",
      "Lane Keep Assist with Lane Departure Warning",
      "Adaptive Cruise Control",
    ],
  },
  {
    id: 7,
    brand: "Hyundai",
    model: "Tucson",
    year: 2023,
    price: 29000,
    image: "https://i.pinimg.com/736x/12/c8/d8/12c8d887aa1dadb67a464d3b78da26e7.jpg",
    fuelType: "Hybrid",
    transmission: "Automatic",
    mileage: 4000,
    seatingCapacity: 5,
    description:
      "The Hyundai Tucson Hybrid combines efficiency with style, offering a futuristic design and impressive fuel economy. The latest generation represents a bold departure from its predecessor with its parametric design elements and spacious, tech-focused interior. The hybrid powertrain delivers excellent fuel efficiency without compromising on performance, making it a compelling option in the competitive compact SUV segment.",
    features: [
      "Digital Key",
      "Panoramic Sunroof",
      "Remote Smart Parking Assist",
      "Bose Premium Audio",
      "Highway Driving Assist",
      "10.25-inch Touchscreen Navigation",
      "Blind-Spot View Monitor",
      "Surround View Monitor",
      "Wireless Device Charging",
      "Hyundai SmartSense Safety Suite",
    ],
  },
  {
    id: 8,
    brand: "Audi",
    model: "Q5",
    year: 2022,
    price: 48000,
    image: "https://i.pinimg.com/736x/fb/0e/0c/fb0e0cc9f3f07a067606d89b7a80d087.jpg",
    fuelType: "Gasoline",
    transmission: "Automatic",
    mileage: 9000,
    seatingCapacity: 5,
    description:
      "The Audi Q5 is a luxury compact SUV with refined handling, a premium interior, and advanced technology features. It exemplifies Audi's commitment to quality craftsmanship and cutting-edge technology in a versatile package. The Q5 offers a smooth, comfortable ride with enough power to make driving engaging, while its well-appointed interior provides a sophisticated environment for both driver and passengers.",
    features: [
      "Virtual Cockpit",
      "Bang & Olufsen Sound",
      "Quattro All-Wheel Drive",
      "Ambient Lighting",
      "Head-Up Display",
      "MMI Touch Response System",
      "Audi Pre Sense Safety Suite",
      "Adaptive Cruise Control with Traffic Jam Assist",
      "Panoramic Sunroof",
      "Ventilated Front Seats",
    ],
  },
  {
    id: 9,
    brand: "Subaru",
    model: "Outback",
    year: 2023,
    price: 34000,
    image: "https://i.pinimg.com/736x/3b/e6/11/3be611d57139142b4153524a7c9d7f1b.jpg",
    fuelType: "Gasoline",
    transmission: "Automatic",
    mileage: 6000,
    seatingCapacity: 5,
    description:
      "The Subaru Outback is a versatile wagon-like SUV with standard all-wheel drive and excellent off-road capability. It combines the practicality of a wagon with the capability of an SUV, making it perfect for outdoor enthusiasts and families alike. With its raised ground clearance, rugged body cladding, and advanced all-wheel-drive system, the Outback is ready for adventures while still providing a comfortable, car-like driving experience on paved roads.",
    features: [
      "X-Mode Off-Road Assist",
      "11.6-inch Touchscreen",
      "EyeSight Driver Assist",
      "Starlink Safety",
      "Power Liftgate",
      "Wilderness Trim Option",
      "Roof Rails with Integrated Crossbars",
      "DriverFocus Distraction Mitigation System",
      "180-Degree Front View Monitor",
      "Dual-Zone Climate Control",
    ],
  },
  {
    id: 10,
    brand: "Mazda",
    model: "CX-5",
    year: 2022,
    price: 31000,
    image: "https://i.pinimg.com/736x/cf/95/76/cf9576dee02c6c63a1d83469dd6140d2.jpg",
    fuelType: "Gasoline",
    transmission: "Automatic",
    mileage: 11000,
    seatingCapacity: 5,
    description:
      "The Mazda CX-5 stands out with its upscale interior, engaging driving dynamics, and sleek exterior design. It brings a level of refinement and driving pleasure that's uncommon in the compact SUV segment. The premium materials, thoughtful design, and attention to detail in the cabin create an environment that rivals luxury brands, while the responsive handling and precise steering make every drive enjoyable.",
    features: [
      "G-Vectoring Control",
      "Mazda Connect Infotainment",
      "Bose Audio",
      "Heated Front and Rear Seats",
      "Traffic Sign Recognition",
      "Mazda Radar Cruise Control with Stop & Go",
      "360° View Monitor",
      "Active Driving Display",
      "Nappa Leather Upholstery",
      "Power-Folding Side Mirrors",
    ],
  },
  {
    id: 11,
    brand: "Kia",
    model: "Telluride",
    year: 2023,
    price: 44000,
    image: "https://i.pinimg.com/736x/f5/cd/0c/f5cd0c4ec895660b0934e374ea0735af.jpg",
    fuelType: "Gasoline",
    transmission: "Automatic",
    mileage: 5000,
    seatingCapacity: 8,
    description:
      "The Kia Telluride is a spacious three-row SUV with a luxurious feel, powerful engine, and comprehensive safety features. Since its introduction, the Telluride has earned numerous accolades for its combination of style, space, and value. It offers a commanding presence on the road with its bold design, while the interior provides premium comfort for up to eight passengers and plenty of cargo space for family adventures.",
    features: [
      "Dual Sunroof",
      "Harman Kardon Audio",
      "Heated and Ventilated Seats",
      "Highway Driving Assist",
      "Safe Exit Assist",
      "10.25-inch Touchscreen Navigation",
      "Head-Up Display",
      "Blind-Spot View Monitor",
      "Driver Talk In-Car Intercom",
      "Quiet Mode for Rear Passengers",
    ],
  },
  {
    id: 12,
    brand: "Volkswagen",
    model: "Tiguan",
    year: 2022,
    price: 33000,
    image: "https://i.pinimg.com/736x/c9/e2/bb/c9e2bb1e9318d8e10604f9a99c3d0c0d.jpg",
    fuelType: "Gasoline",
    transmission: "Automatic",
    mileage: 9000,
    seatingCapacity: 7,
    description:
      "The Volkswagen Tiguan offers European styling, a spacious interior, and available third-row seating in a compact SUV package. It stands out in the crowded compact SUV segment with its refined driving characteristics and versatile interior configuration. The Tiguan provides a solid, substantial feel on the road that's characteristic of German engineering, while its clean, understated design has a timeless quality that will age well.",
    features: [
      "Digital Cockpit",
      "Fender Premium Audio",
      "Panoramic Sunroof",
      "Remote Start",
      "Adaptive Cruise Control",
      "IQ.DRIVE Driver Assistance Technology",
      "Third-Row Seating",
      "Climatronic® Dual-Zone Climate Control",
      "Volkswagen Car-Net®",
      "Hands-free Easy Open and Easy Close Liftgate",
    ],
  },
  {
    id: 13,
    brand: "Nissan",
    model: "Rogue",
    year: 2023,
    price: 30000,
    image: "https://i.pinimg.com/736x/29/40/d1/2940d11e14564f0401a2347cd0697849.jpg",
    fuelType: "Gasoline",
    transmission: "Automatic",
    mileage: 7000,
    seatingCapacity: 5,
    description:
      "The Nissan Rogue combines comfort, efficiency, and practicality with a stylish design and user-friendly technology. The latest generation represents a significant improvement over its predecessor with more refined styling, a higher-quality interior, and enhanced driving dynamics. The Rogue offers a comfortable, quiet ride and a flexible cargo area that adapts to various needs, making it an excellent choice for families and commuters alike.",
    features: [
      "ProPILOT Assist",
      "Divide-N-Hide Cargo System",
      "Bose Premium Audio",
      "Wireless Apple CarPlay",
      "Motion Activated Liftgate",
      "Tri-Zone Temperature Control",
      "Intelligent Around View Monitor",
      "Quilted Semi-Aniline Leather Seats",
      "Head-Up Display",
      "Nissan Safety Shield 360",
    ],
  },
  {
    id: 14,
    brand: "Jeep",
    model: "Grand Cherokee",
    year: 2022,
    price: 47000,
    image: "https://i.pinimg.com/736x/03/e9/6b/03e96b4c5ead49b8ee4d7a8727cd9d64.jpg",
    fuelType: "Gasoline",
    transmission: "Automatic",
    mileage: 8000,
    seatingCapacity: 5,
    description:
      "The Jeep Grand Cherokee offers a blend of off-road capability, on-road comfort, and upscale amenities. The latest generation builds on the model's legacy with improved refinement, technology, and capability. It maintains its reputation as one of the most capable SUVs in its class while adding luxury features and advanced technology that make it equally at home on city streets or rugged trails.",
    features: [
      "Quadra-Drive II 4x4",
      "10.1-inch Touchscreen",
      "McIntosh Audio System",
      "Parallel and Perpendicular Park Assist",
      "Night Vision",
      "Quadra-Lift Air Suspension",
      "Front Passenger Interactive Display",
      "Digital Rearview Mirror",
      "Intersection Collision Assist",
      "Active Driving Assist",
    ],
  },
  {
    id: 15,
    brand: "Lexus",
    model: "RX",
    year: 2023,
    price: 52000,
    image: "https://i.pinimg.com/736x/24/d1/40/24d140b48f3ec666820f68f919342474.jpg",
    fuelType: "Hybrid",
    transmission: "Automatic",
    mileage: 4000,
    seatingCapacity: 5,
    description:
      "The Lexus RX Hybrid delivers a smooth, quiet ride with excellent fuel efficiency and a luxurious interior. As one of the pioneers in the luxury crossover segment, the RX continues to set standards for comfort, reliability, and refinement. The hybrid powertrain provides a perfect balance of performance and efficiency, while the cabin offers a serene environment with high-quality materials and thoughtful design.",
    features: [
      "Mark Levinson Audio",
      "Head-Up Display",
      "Panoramic View Monitor",
      "Lexus Safety System+",
      "Power-Folding Rear Seats",
      "Touch-Free Power Rear Door",
      "Lexus Interface with 14-inch Touchscreen",
      "Digital Latch with Safe Exit Assist",
      "Traffic Jam Assist",
      "Digital Rearview Mirror",
    ],
  },
  {
    id: 16,
    brand: "Mercedes-Benz",
    model: "C-Class",
    year: 2022,
    price: 49000,
    image: "https://i.pinimg.com/736x/a0/45/3e/a0453e5fb83f490368a07b1a9c588593.jpg",
    fuelType: "Gasoline",
    transmission: "Automatic",
    mileage: 6000,
    seatingCapacity: 5,
    description:
      "The Mercedes-Benz C-Class offers a perfect blend of luxury, technology, and performance in a compact sedan package. The latest generation takes design cues from the flagship S-Class, bringing an even more upscale look and feel to the compact luxury segment. The interior is a technological showcase with a large central touchscreen, digital instrument cluster, and ambient lighting, while the driving experience balances comfort and sportiness.",
    features: [
      "MBUX Infotainment",
      "Burmester Surround Sound",
      "64-Color Ambient Lighting",
      "Augmented Video Navigation",
      "Energizing Comfort",
      "Fingerprint Scanner",
      "Digital Light Headlamps",
      "AIRMATIC Air Suspension",
      "Rear-Axle Steering",
      "Car-to-X Communication",
    ],
  },
  {
    id: 17,
    brand: "Toyota",
    model: "RAV4",
    year: 2023,
    price: 32000,
    image: "https://i.pinimg.com/736x/c8/dc/0c/c8dc0ccbd06b6a16186ddf279955aeae.jpg",
    fuelType: "Hybrid",
    transmission: "Automatic",
    mileage: 5000,
    seatingCapacity: 5,
    description:
      "The Toyota RAV4 Hybrid combines practicality with efficiency, offering excellent fuel economy and a spacious interior. As one of the most popular compact SUVs on the market, the RAV4 Hybrid delivers a compelling package of utility, reliability, and eco-friendly performance. Its rugged styling stands out in a crowded segment, while the hybrid powertrain provides smooth, efficient operation with enough power for confident driving.",
    features: [
      "Digital Rearview Mirror",
      "JBL Premium Audio",
      "Wireless Charging",
      "Hands-Free Power Liftgate",
      "Multi-Terrain Select",
      "Toyota Safety Sense 2.0",
      "Bird's Eye View Camera",
      "Ventilated Front Seats",
      "SofTex-Trimmed Seats",
      "Smart Key System",
    ],
  },
  {
    id: 18,
    brand: "Honda",
    model: "CR-V",
    year: 2022,
    price: 33000,
    image: "https://i.pinimg.com/736x/9e/0c/83/9e0c833d51bfab5c5ad5cfdc3f4ef7c0.jpg",
    fuelType: "Hybrid",
    transmission: "Automatic",
    mileage: 7000,
    seatingCapacity: 5,
    description:
      "The Honda CR-V Hybrid offers exceptional fuel efficiency, a comfortable ride, and plenty of cargo space. It builds on the CR-V's reputation for practicality and reliability by adding an efficient hybrid powertrain that enhances both performance and fuel economy. The spacious interior provides comfortable seating for five adults and versatile cargo options, while the refined ride quality makes it ideal for daily commuting and longer trips.",
    features: [
      "Honda Sensing Suite",
      "Hands-Free Access Power Tailgate",
      "Wireless Phone Charger",
      "Rain-Sensing Wipers",
      "Heated Steering Wheel",
      "9-inch Touchscreen Display",
      "Bose Premium Sound System",
      "Wireless Apple CarPlay and Android Auto",
      "Driver Attention Monitor",
      "Walk Away Auto Lock",
    ],
  },
  {
    id: 19,
    brand: "Ford",
    model: "Mustang",
    year: 2023,
    price: 40000,
    image: "https://i.pinimg.com/736x/e9/72/3b/e9723bce858f416b51059687b4767b72.jpg",
    fuelType: "Gasoline",
    transmission: "Manual",
    mileage: 3000,
    seatingCapacity: 4,
    description:
      "The Ford Mustang delivers thrilling performance, iconic styling, and modern technology in a classic American sports car. For over five decades, the Mustang has represented American performance and freedom, and the current generation continues this legacy with powerful engine options, aggressive styling, and advanced features. Whether equipped with the efficient EcoBoost engine or the thundering V8, the Mustang provides an engaging driving experience that stays true to its heritage.",
    features: [
      "Track Apps",
      "Active Valve Performance Exhaust",
      "12-inch Digital Instrument Cluster",
      "SYNC 3",
      "MagneRide Damping System",
      "Line Lock",
      "Launch Control",
      "Recaro Sport Seats",
      "B&O Sound System",
      "FordPass Connect",
    ],
  },
  {
    id: 20,
    brand: "Chevrolet",
    model: "Corvette",
    year: 2022,
    price: 65000,
    image: "https://i.pinimg.com/736x/21/7f/bc/217fbc18f3715fd9c3c8880622153ff1.jpg",
    fuelType: "Gasoline",
    transmission: "Automatic",
    mileage: 4000,
    seatingCapacity: 2,
    description:
      "The Chevrolet Corvette offers supercar performance with its mid-engine design, powerful V8, and advanced technology. The eighth-generation Corvette represents the most radical redesign in the model's history, moving to a mid-engine layout that transforms both its appearance and driving dynamics. This configuration allows for exceptional handling and acceleration that rivals exotic cars costing much more, while still maintaining the Corvette's reputation for value and everyday usability.",
    features: [
      "Performance Data Recorder",
      "Head-Up Display",
      "Magnetic Selective Ride Control",
      "Front Lift System",
      "Bose Performance Series Audio",
      "8-Speed Dual-Clutch Transmission",
      "Z51 Performance Package",
      "Rear Camera Mirror",
      "Wireless Apple CarPlay and Android Auto",
      "Custom Leather-Wrapped Interior",
    ],
  },
  {
    id: 21,
    brand: "Porsche",
    model: "911",
    year: 2023,
    price: 115000,
    image: "https://i.pinimg.com/736x/98/c0/6d/98c06dd536b4397ba01e55e0e9d3f0b4.jpg",
    fuelType: "Gasoline",
    transmission: "Automatic",
    mileage: 2000,
    seatingCapacity: 4,
    description:
      "The Porsche 911 is an iconic sports car that combines exhilarating performance with everyday usability. With its distinctive silhouette and rear-engine layout, the 911 has evolved over decades while maintaining its core character. The latest generation offers cutting-edge technology, refined interiors, and a range of powerful turbocharged engines, all while preserving the unique driving experience that has made the 911 a benchmark in the sports car world.",
    features: [
      "Porsche Active Suspension Management",
      "Sport Chrono Package",
      "Porsche Communication Management",
      "Burmester High-End Surround Sound",
      "Adaptive Sport Seats Plus",
      "Rear-Axle Steering",
      "LED Matrix Headlights",
      "Lane Change Assist",
      "Night Vision Assist",
      "Porsche Dynamic Chassis Control",
    ],
  },
  {
    id: 22,
    brand: "Audi",
    model: "e-tron",
    year: 2023,
    price: 68000,
    image: "https://i.pinimg.com/736x/57/f4/5f/57f45f2f85c557bce9a1113e6007852e.jpg",
    fuelType: "Electric",
    transmission: "Automatic",
    mileage: 3000,
    seatingCapacity: 5,
    description:
      "The Audi e-tron is a premium all-electric SUV that combines luxury, technology, and sustainable mobility. With its refined design, spacious interior, and impressive range, the e-tron delivers the Audi experience in an electric package. Advanced features like regenerative braking, fast-charging capability, and a sophisticated thermal management system ensure optimal performance in various conditions, while the quiet, powerful electric drivetrain provides a smooth and responsive driving experience.",
    features: [
      "Virtual Mirrors",
      "Dual Touchscreen MMI System",
      "Bang & Olufsen 3D Sound",
      "Air Quality Package with Ionizer",
      "Adaptive Air Suspension",
      "Matrix LED Headlights",
      "Panoramic Glass Sunroof",
      "Four-Zone Climate Control",
      "Audi Phone Box with Wireless Charging",
      "Audi Pre Sense 360°",
    ],
  },
  {
    id: 23,
    brand: "Volvo",
    model: "XC90",
    year: 2022,
    price: 56000,
    image: "https://i.pinimg.com/736x/a4/4c/06/a44c06a295aebc6225da6d07344c6256.jpg",
    fuelType: "Hybrid",
    transmission: "Automatic",
    mileage: 8000,
    seatingCapacity: 7,
    description:
      "The Volvo XC90 is a luxury three-row SUV that emphasizes safety, Scandinavian design, and advanced technology. Available with a plug-in hybrid powertrain, the XC90 offers a compelling blend of performance and efficiency. The interior features premium materials, a minimalist aesthetic, and thoughtful details that create a serene environment. With its comprehensive safety systems and family-friendly features, the XC90 exemplifies Volvo's commitment to protecting occupants while providing a premium driving experience.",
    features: [
      "Pilot Assist Semi-Autonomous Drive",
      "Bowers & Wilkins Premium Sound",
      "9-inch Sensus Touchscreen",
      "Four-Zone Electronic Climate Control",
      "Hands-Free Power Tailgate",
      "360° Surround View Camera",
      "Graphical Head-Up Display",
      "Integrated Booster Cushion",
      "Air Suspension",
      "Orrefors Crystal Gear Selector",
    ],
  },
  {
    id: 24,
    brand: "Genesis",
    model: "GV80",
    year: 2023,
    price: 59000,
    image: "https://i.pinimg.com/736x/04/67/e5/0467e55eefb0d72c9139476e087f26bf.jpg",
    fuelType: "Gasoline",
    transmission: "Automatic",
    mileage: 4000,
    seatingCapacity: 5,
    description:
      "The Genesis GV80 is a luxury midsize SUV that combines distinctive styling, premium features, and exceptional value. As the first SUV from Genesis, the GV80 makes a strong impression with its bold exterior design and opulent interior. Advanced technology, refined powertrains, and a comprehensive suite of safety features create a compelling package that challenges established luxury brands. The attention to detail and focus on the overall ownership experience set the GV80 apart in the competitive luxury SUV segment.",
    features: [
      "Ergo Motion Driver's Seat",
      "14.5-inch HD Navigation System",
      "Lexicon Premium Audio",
      "Remote Smart Parking Assist",
      "Road Active Noise Cancellation",
      "Electronically Controlled Suspension with Road Preview",
      "Blind-Spot View Monitor",
      "Augmented Reality Navigation",
      "Smart Cruise Control with Machine Learning",
      "Genesis Digital Key",
    ],
  },
  {
    id: 25,
    brand: "Acura",
    model: "MDX",
    year: 2022,
    price: 48000,
    image: "https://i.pinimg.com/736x/4b/e2/5d/4be25db56a1ed74bf7d2c917201d3683.jpg",
    fuelType: "Gasoline",
    transmission: "Automatic",
    mileage: 6000,
    seatingCapacity: 7,
    description:
      "The Acura MDX is a luxury three-row SUV that balances performance, comfort, and technology. The latest generation features a more athletic design, improved driving dynamics, and a more upscale interior. With its spacious cabin, versatile seating configurations, and comprehensive safety features, the MDX is well-suited for families seeking a premium driving experience. The available Super Handling All-Wheel Drive system enhances both performance and all-weather capability.",
    features: [
      "Precision Cockpit Digital Instrument Cluster",
      "ELS Studio 3D Premium Audio",
      "16-Way Power Front Seats with Massage",
      "CabinTalk In-Car PA System",
      "Adaptive Damper System",
      "Panoramic Moonroof",
      "AcuraWatch Safety Suite",
      "Traffic Jam Assist",
      "Wireless Charging Pad",
      "Multi-Function Second-Row with Removable Middle Seat",
    ],
  },
  {
    id: 26,
    brand: "Infiniti",
    model: "QX60",
    year: 2023,
    price: 51000,
    image: "https://i.pinimg.com/736x/b2/6a/ba/b26aba9a44d45152c71a050686d9afc3.jpg",
    fuelType: "Gasoline",
    transmission: "Automatic",
    mileage: 5000,
    seatingCapacity: 7,
    description:
      "The Infiniti QX60 is a luxury three-row SUV that focuses on comfort, elegance, and family-friendly features. The redesigned model offers a more premium experience with its refined styling, upscale interior, and enhanced technology. The spacious cabin provides comfortable seating for seven passengers, while thoughtful details like easy access to the third row make the QX60 practical for everyday use. With a smooth powertrain and a comprehensive suite of driver assistance features, the QX60 delivers a relaxed and confident driving experience.",
    features: [
      "ProPILOT Assist with Navi-link",
      "Massage Front Seats",
      "Motion Activated Liftgate",
      "Bose Performance Series Audio",
      "Tri-Zone Climate Control",
      "Second-Row Captain's Chairs Option",
      "Wireless Apple CarPlay",
      "Around View Monitor with Moving Object Detection",
      "Digital Rearview Mirror",
      "Intelligent All-Wheel Drive",
    ],
  },
  {
    id: 27,
    brand: "Land Rover",
    model: "Defender",
    year: 2022,
    price: 58000,
    image: "https://i.pinimg.com/736x/77/3c/e6/773ce600245fd3ae7cf661f7cc08c596.jpg",
    fuelType: "Gasoline",
    transmission: "Automatic",
    mileage: 7000,
    seatingCapacity: 5,
    description:
      "The Land Rover Defender is an iconic off-road vehicle reimagined for the modern era with enhanced capability, technology, and refinement. While maintaining the rugged character and go-anywhere ability of its predecessor, the new Defender adds comfort and convenience features that make it suitable for everyday use. Advanced off-road technologies like Terrain Response 2 and configurable terrain response help the Defender tackle challenging conditions, while the durable yet premium interior balances functionality with luxury.",
    features: [
      "Terrain Response 2",
      "Wade Sensing",
      "Electronic Air Suspension",
      "Pivi Pro Infotainment",
      "ClearSight Ground View",
      "Configurable Terrain Response",
      "Activity Key",
      "Meridian Sound System",
      "Sliding Panoramic Roof",
      "Expedition Roof Rack",
    ],
  },
  {
    id: 28,
    brand: "Cadillac",
    model: "Escalade",
    year: 2023,
    price: 82000,
    image: "https://i.pinimg.com/736x/31/90/cc/3190cc8f77b46e88b5c6b1d66f3fa80f.jpg",
    fuelType: "Gasoline",
    transmission: "Automatic",
    mileage: 4000,
    seatingCapacity: 7,
    description:
      "The Cadillac Escalade is a full-size luxury SUV that makes a bold statement with its imposing presence, opulent interior, and cutting-edge technology. The latest generation features a curved OLED display that spans much of the dashboard, providing a futuristic and premium user interface. With its powerful V8 engine, available Super Cruise hands-free driving system, and sophisticated suspension, the Escalade delivers a commanding driving experience. The spacious three-row interior offers exceptional comfort and versatility for passengers and cargo.",
    features: [
      "38-inch Curved OLED Display",
      "Super Cruise Hands-Free Driving",
      "AKG Studio Reference 36-Speaker Audio",
      "Magnetic Ride Control",
      "Air Ride Adaptive Suspension",
      "Night Vision",
      "Rear Seat Entertainment System",
      "Conversation Enhancement",
      "Soft-Close Doors",
      "Refrigerated Center Console",
    ],
  },
  {
    id: 29,
    brand: "Lincoln",
    model: "Navigator",
    year: 2022,
    price: 78000,
    image: "https://i.pinimg.com/736x/31/90/cc/3190cc8f77b46e88b5c6b1d66f3fa80f.jpg",
    fuelType: "Gasoline",
    transmission: "Automatic",
    mileage: 5000,
    seatingCapacity: 7,
    description:
      "The Lincoln Navigator is a full-size luxury SUV that emphasizes comfort, refinement, and American luxury. With its powerful twin-turbocharged engine, spacious three-row interior, and advanced technology, the Navigator provides a first-class travel experience. The cabin features premium materials, adjustable ambient lighting, and available Perfect Position seats with massage functionality. Thoughtful details and a comprehensive suite of driver assistance features make the Navigator an ideal vehicle for long journeys and everyday luxury.",
    features: [
      "30-Way Perfect Position Seats with Massage",
      "Revel Ultima 3D Audio System",
      "Lincoln ActiveGlide Hands-Free Highway Driving",
      "Illuminated Lincoln Star Grille",
      "Power-Deployable Running Boards",
      "Head-Up Display",
      "Phone As A Key Technology",
      "Adaptive Pixel LED Headlamps",
      "Panoramic Vista Roof",
      "Lincoln Play Rear-Seat Entertainment System",
    ],
  },
  {
    id: 30,
    brand: "GMC",
    model: "Sierra",
    year: 2023,
    price: 56000,
    image: "https://i.pinimg.com/736x/32/18/2f/32182f7b81f40e65c814ef839c72ae5a.jpg",
    fuelType: "Gasoline",
    transmission: "Automatic",
    mileage: 3000,
    seatingCapacity: 5,
    description:
      "The GMC Sierra is a full-size pickup truck that combines capability, technology, and premium features. The latest generation offers innovative features like the MultiPro tailgate, which provides six different functions to improve access, loading, and work utility. Inside, the Sierra can be equipped with luxury amenities and advanced technology, including a large infotainment display and a comprehensive suite of driver assistance features. With various powertrain options and impressive towing capacity, the Sierra is ready for work and play.",
    features: [
      "MultiPro Tailgate",
      "CarbonPro Carbon Fiber Composite Bed",
      "Super Cruise Hands-Free Driving",
      "13.4-inch Infotainment Screen",
      "12.3-inch Digital Instrument Cluster",
      "15-inch Head-Up Display",
      "Transparent Trailer View",
      "ProGrade Trailering System",
      "Adaptive Ride Control",
      "Power-Retractable Assist Steps",
    ],
  },
]

// Function to get all cars
export async function getCars() {
  // Simulate API delay
  await new Promise((resolve) => setTimeout(resolve, 500))
  return cars
}

// Function to get a car by ID
export async function getCarById(id: number) {
  // Simulate API delay
  await new Promise((resolve) => setTimeout(resolve, 300))
  return cars.find((car) => car.id === id) || null
}
